---
aur_packages:
  - aur-auto-vote-git
  - autojump-rs
  - bitwarden-cli
  - clion
  - drawio-desktop
  - f5vpn
  - firefox-tridactyl-native
  - google-chrome
  - homematic-manager-bin
  - informant
  - intellij-idea-ultimate-edition
  - intellij-idea-ultimate-edition-jre
  - k3s-bin
  - krew-bin
  - kubeadm-bin
  - kubectl-bin
  - libinput-gestures
  - lscolors-git
  - ltunify-git
  - masterpdfeditor-free
  - numix-icon-theme-git # For Dunst
  - obsidian-appimage
  - openvpn-update-systemd-resolved
  - pacman-cleanup-hook
  - polybar
  - siji-git # Font for the polybar example config file
  - slack-desktop
  - spotify
  - systemd-boot-pacman-hook
  - teams
  - thinkfan
  - urxvt-resize-font-git
  - urxvt-tabbedex
  - visual-studio-code-bin
  - yay
  - yourkit
  - zoom

config_folder: /home/{{ username }}/.config

hostname: lars-laptop

lingering_users:
  - "{{ username }}"

locales:
  - de_DE
  - de_DE.UTF-8
  - en_US
  - en_US.UTF-8

pacman_packages:
  - acpi_call # For TLP
  - alacritty
  - alsa-utils
  - ansible
  - asp
  - autoconf
  - autorandr
  - base
  - base-devel
  - binutils
  - bluez
  - bluez-utils
  - bspwm
  - btrfs-progs
  - calibre
  - chezmoi
  - compsize # To calculate BTRFS compression stats
  - crda
  - cups
  - cups-pdf
  - delve
  - discord
  - dnsmasq
  - docker
  - docker-compose
  - dunst
  - earlyoom
  - ebtables
  - ethtool
  - fakeroot
  - fd
  - file
  - firefox
  - firefox-tridactyl
  - flameshot
  - fuse2 # Needed for restic mount which uses fusermount and not fusermount3
  - fwupd
  - fzf
  - gdb
  - git
  - go
  - grep
  - hcloud
  - htop
  - hunspell-de
  - intel-gpu-tools
  - intel-ucode
  - iwd
  - jdk-openjdk
  - jdk11-openjdk
  - jdk8-openjdk
  - k9s
  - kbd
  - kubectx
  - kustomize
  - lib32-vulkan-intel
  - libreoffice-fresh
  - libvirt
  - light
  - linux
  - linux-firmware
  - linux-lts
  - lvm2
  - lynx
  - man
  - maven
  - ncdu
  - nemo
  - neovim
  - nethogs
  - newsboat
  - nodejs
  - notepadqq
  - npm
  - nss-mdns
  - openjdk-src
  - openjdk11-src
  - openjdk8-src
  - openssh
  - openvpn
  - p7zip
  - pacman-contrib # For pacdiff
  - pavucontrol
  - physlock
  - picom
  - pinta
  - pkgstats
  - podman
  - powertop
  - profile-sync-daemon
  - pulseaudio
  - pulseaudio-alsa
  - pulseaudio-bluetooth
  - python-gobject # Optional dependency of redshift, needed for redshift-gtk
  - qemu
  - ranger
  - redshift
  - reflector
  - restic
  - ripgrep
  - rofi
  - rofi-calc
  - rsync
  - rust-analyzer
  - rustup
  - sane
  - shellcheck
  - shellharden
  - smartmontools # For TLP
  - snap-pac
  - snapper
  - sof-firmware # Required for Audio on T14 as of 2020-07-29
  - steam
  - strace
  - subversion
  - sudo
  - sxhkd
  - systemd-resolvconf
  - tcpdump
  - terraform
  - tlp
  - tmux
  - tpacpi-bat # For battery charging thresholds for TLP
  - ttf-dejavu
  - unzip
  - urxvt-perls
  - util-linux
  - veracrypt
  - vim
  - virt-manager
  - vlc
  - vulkan-intel
  - wget
  - wireguard-tools
  - wireshark-qt
  - wmname
  - xf86-input-wacom
  - xf86-input-synaptics
  - xf86-video-intel
  - xorg
  - xorg-xinit
  - xsel
  - youtube-dl
  - zathura
  - zathura-pdf-mupdf
  - zsh

timezone: Europe/Berlin

username: lars

# "informant" is required so informant doesn't require root
# "input" is required for libinput-gestures
# "video" is required for the light app
user_groups: docker,informant,input,libvirt,video,wheel
