---
- name: Ensure systemd-network config files are in place
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/network/{{ item }}
    owner: root
    group: root
    mode: 0644
  notify: Restart systemd-networkd
  loop:
    - 20-wired.network
    - 25-wireless.network

- name: Ensure network services are enabled and running
  become: yes
  systemd:
    name: systemd-networkd
    enabled: yes
    state: started
