---
- name: Ensure earlyoom is installed
  pacman:
    name: earlyoom
    state: present

- name: Ensure earlyoom service is enabled and running
  become: yes
  systemd:
    name: earlyoom
    enabled: yes
    state: started
