---
- name: Ensure physlock is installed
  pacman:
    name: physlock
    state: present

- name: Ensure services and configuration are in place
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: "physlock.service.j2", dest: "/etc/systemd/system/physlock.service" }
    - { src: "sleep.conf.j2",       dest: "/etc/systemd/sleep.conf" }
    - { src: "logind.conf.j2",      dest: "/etc/systemd/logind.conf" }
    - { src: "lowbat.rules.j2",     dest: "/etc/udev/rules.d/99-lowbat.rules" }

# This should not be in state "started" because that'll immediately lock the screen
- name: Ensure physlock service is enabled and running
  become: yes
  systemd:
    name: physlock
    enabled: yes
