---
- name: Ensure X11 libinput config file is in place
  become: yes
  template:
    src: 99-libinput-custom-config.conf.j2
    dest: /etc/X11/xorg.conf.d/99-libinput-custom-config.conf
    owner: root
    group: root
    mode: 0644
