---
- name: Setup the keymap and console
  become: yes
  template:
    src: vconsole.conf.j2
    dest: /etc/vconsole.conf
    owner: root
    group: root
    mode: 0644
  notify: Rebuild mkinitcpio

- name: Ensure keymap for X11 is set
  become: yes
  command: localectl set-x11-keymap de neo --no-convert
