---
- hosts: all
  module_defaults:
    file:
      owner: "{{ username }}"
      group: "{{ username }}"
    copy:
      owner: "{{ username }}"
      group: "{{ username }}"
    template:
      owner: "{{ username }}"
      group: "{{ username }}"
  roles:
    - yay
#    - upgrade
#    - packages

    - aur-auto-vote
    - bluetooth
    - bootloader
    - chezmoi
    - fonts
    - fstrim
    - hibernate
    - hostname
    - iwd
    - keymap
    - libvirt
    - libinput
    - locale
    - pacman
    - pcspeaker
    - pkgstats
    - podman
    - printer
    - reflector
    - restic
    - root
    - screen-tearing
    - snapper
    - ssh
    - ssh-agent
    - sudo
    - swap
#    - synaptics -> using libinput
    - systemd-logind
    - systemd-networkd
    - systemd-oomd
    - systemd-resolved
    - time
    - tlp
    - user
    - watchdog
